---
title: "What did the presidents say at their inauguration?"
output: html_notebook
---
# Step 0: check and install needed packages. Load the libraries and functions. 
```{r}
packages.used=c(
  "dplyr",
  "readr",
  "DT",
  "tibble",
  "htmlwidgets",
  "xlsx",         # packages used for importing xlsx files
  "rJava",
  "xlsxjars",     
  "tm", # text mining package used for tf-idf
  "wordcloud",
  "RColorBrewer",
  "tydytext",
  "maps", # for mapping
  "rworldmap"
  )

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

# load packages
library("dplyr")
library("readr")
library("DT")
library("tibble")
library("htmlwidgets")
library("xlsx")
library("rJava")
library("xlsxjars")
library("tm")
library(tm)
library(wordcloud)
library(RColorBrewer)
library(dplyr)
library(tidytext)
```
# Step 1: get inaugural speeches and metadata into dataframe
```{r}
print(paste("You are working from ", getwd()))

inaug.list=read.xlsx(file.path("..","data","InaugurationInfo.xlsx",fsep = .Platform$file.sep),1)
speech.list=rbind(inaug.list)
speech.list$type=c(rep("inaugural", nrow(inaug.list)))
speech.list$id = c(seq(nrow(speech.list)))
speech.list$path=file.path("..","data","InauguralSpeeches",
                            paste0("inaug",speech.list$File,"-",speech.list$Term,".txt"),
                            fsep = .Platform$file.sep)
```
## Step 1.1: loop over text files to get speech text into dataframe
```{r, message=FALSE, warning=FALSE}
for(i in seq(nrow(speech.list))) {
  speech_text = paste(readLines(speech.list$path[i], n=-1, skipNul=TRUE, warn = FALSE), collapse = " ")
  speech.list$fulltext[i]=speech_text
  speech.list$textdoc[i]<-PlainTextDocument(speech_text,
                                           author = speech.list$President,
                                           description = "inaugural address",
                                           id = as.character(i),
                                           language = "eng")
}
```
## Step 1.2: get country and region names
```{r}
require('maps')
cities = tolower(substr(us.cities$name,1,nchar(us.cities$name)-3)) # get city names
```
## Step 1.3: count occurances
```{r}
ds = DirSource(directory = file.path("..","data","InauguralSpeeches",fsep = .Platform$file.sep),
               pattern = "*.txt",
               mode = "text")
speech.corpus = VCorpus(ds)
control_list <- list(removePunctuation = TRUE,
                     removeWords = stopwords("english"),
                     tolower = TRUE,
                     removeNumbers = TRUE,
                     stripWhitespace = TRUE,
                     PlainTextDocument = TRUE)
speech.tdm = TermDocumentMatrix(speech.corpus, control = control_list)
```
Sp
```{r}
countries = tolower(unique(world.cities$country.etc))
continents = c("europe","asia","africa")

control_list <- list(dictionary = countries)
tf = termFreq(a,control = control_list)
```
Sep
```{r}
tdm.tidy=tidy(speech.tdm)
tdm.overall=summarise(group_by(tdm.tidy, term), sum(count))
```

Sep
```{r}
countries_mentioned <- names(as.list(tf[tf!=0]))
```

Sep
```{r}
# filled map showing Republican vote in 1900
# (figure 6 in the reference)

world.to.map <- match.map("world", countries_mentioned)
x <- countries[world.to.map]
gray.colors <- function(n) gray(rev(0:(n - 1))/n)
color <- gray.colors(100)[floor(x)]
map("world", fill = TRUE, col = color); map("world", add = TRUE)
```

```{r}
library(rworldmap)
require(countrycode)

theCountries <- countrycode(countries_mentioned,'country.name','iso3c')
# These are the ISO3 names of the countries you'd like to plot in red

malDF <- data.frame(country = theCountries,
  mentioned = c(rep(length(theCountries))))

malMap <- joinCountryData2Map(malDF, joinCode = "ISO3",
  nameJoinColumn = "country")
# This will join your malDF data.frame to the country map data

mapCountryData(malMap, nameColumnToPlot="mentioned", catMethod = "categorical",
  missingCountryCol = gray(.8))
# And this will plot it, with the trick that the color palette's first
# color is red

```

